In [1]:
print("hello")

hello


In [2]:
5/2

2.5

In [3]:
5//2

2

In [4]:
for i in range(3):
    print(i)

0
1
2


In [5]:
range(3)

range(0, 3)

In [6]:
print(list(range(3)))

[0, 1, 2]


In [8]:
import numpy as np

In [9]:
%%time
a = [i for i in range(100000)]
b = [i for i in range(100000)]

Wall time: 13 ms


In [10]:
%%time
c=[]
for i in range(len(a)):
    c.append(a[i]+2*b[i])

Wall time: 40 ms


In [11]:
%%time
a =np.arange(100000)
b =np.arange(100000)

Wall time: 3 ms


In [12]:
%%time
c =a+2*b

Wall time: 3 ms


In [13]:
a= np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [14]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [15]:
a=np.zeros((2,2))
print(a)



[[0. 0.]
 [0. 0.]]


In [16]:
b=np.full((2,2),7)
print(b)

[[7 7]
 [7 7]]


In [17]:
c =np.eye(2)
print(c)

[[1. 0.]
 [0. 1.]]


In [18]:
d=np.random.random((2,2))
print(d)

[[0.21624436 0.6876965 ]
 [0.39658013 0.98057173]]


In [19]:
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [20]:
nums=np.arange(8)
print(nums)
print(nums.shape)

[0 1 2 3 4 5 6 7]
(8,)


In [21]:
nums =nums.reshape((2,4))
print('Reshaped:\n',nums)
print(nums.shape)

Reshaped:
 [[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [22]:
nums=nums.reshape((4,-1))
print("Reshaped with -1:\n", nums)
print(nums.shape)

Reshaped with -1:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [23]:
nums = np.arange(8)
print(nums.min())
print(np.min(nums))

0
0


In [24]:
x=np.array([[1,2],
           [3,4]], dtype=np.float64)
y=np.array([[5,6],
           [7,8]], dtype=np.float64)
print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [25]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

v=np.array([9,10])
w=np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

print(x.dot(v))
print(np.dot(x,v))

print(x.dot(y))
print(np.dot(x,y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
x=np.array([[1,2,3],
           [4,5,6,]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x, axis=1))
print(np.max(x,axis=1))

21
[5 7 9]
[ 6 15]
[3 6]


In [28]:
x=np.array([[1,2,3],
            [4,5,6]])
print(np.argmax(x,axis=1))

[2 2]


In [29]:
x=np.array([[1,2,3],
            [4,5,6]])
print(x.shape)

(2, 3)


In [30]:
print((x.max(axis=0)).shape)

(3,)


In [35]:
x=np.array([
           [[1,2,3],
            [4,5,6]],
           [[10,23,33],
           [43,52,16]]
           ])
print(x)
print(x.shape)
print((x.max(axis=1)).shape)
print((x.max(axis=(1,2))))
print((x.max(axis=(1,2))).shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 23 33]
  [43 52 16]]]
(2, 2, 3)
(2, 3)
[ 6 52]
(2,)


In [38]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
print('Original:\n',a)
print('Element (0,0)(a[0][0]):\n',a[0,0])
print('Element (0,0)(a[0,0]):\n',a[0][0])
b = a[:2,1:3]
print('Sliced (a[:2,1:3]):\n', b)
print('Reversing the first row (a[0,::-1]) :\n', a[0,::-1])

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element (0,0)(a[0][0]):
 1
Element (0,0)(a[0,0]):
 1
Sliced (a[:2,1:3]):
 [[2 3]
 [6 7]]
Reversing the first row (a[0,::-1]) :
 [4 3 2 1]


In [43]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
print(a)
b=np.array([0,2,0,1])
print(a[np.arange(4),b])
a[np.arange(4),b]+=10
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
