In [3]:
import numpy as np

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.empty((3,4), dtype='int8')

array([[50,  0, 61,  0],
       [67,  0, 58,  0],
       [92,  0, 80,  0]], dtype=int8)

In [6]:
np.eye(6, dtype='float32')

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [7]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
a.dtype


dtype('int32')

In [9]:
b.dtype

dtype('int32')

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a = np.fromiter([1,2,3,4], dtype='int8')
a

array([1, 2, 3, 4], dtype=int8)

In [13]:
a = np.array([[1,2],[3,4],[5,6]])

In [14]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a[0]

array([1, 2])

In [16]:
a[0][0]

1

In [17]:
a.ndim

2

In [18]:
a.shape

(3, 2)

In [19]:
# size is the total no. of elements which is no.of rows x no. of columns
a.size

6

In [20]:
# returns the size of each element of array in bytes
a.itemsize

4

In [21]:
np.full((10,10),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [22]:
b =np.asarray([1,2,3,4])
print(b)

[1 2 3 4]


In [23]:
c=((1,2),(3,4))
d=np.asarray(c)
print(d)

[[1 2]
 [3 4]]


In [24]:
array= np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
reshaped = array.reshape(2,5)
reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
reshape5 = array.reshape(5,2)
reshape5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
print(np.arange(1,21, dtype='int32'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
print(np.arange(1,21,2, dtype='int64'))

[ 1  3  5  7  9 11 13 15 17 19]


In [29]:
#prints equally spaced 100 values between 1 and 20 
print(np.linspace(1,20,100))

[ 1.          1.19191919  1.38383838  1.57575758  1.76767677  1.95959596
  2.15151515  2.34343434  2.53535354  2.72727273  2.91919192  3.11111111
  3.3030303   3.49494949  3.68686869  3.87878788  4.07070707  4.26262626
  4.45454545  4.64646465  4.83838384  5.03030303  5.22222222  5.41414141
  5.60606061  5.7979798   5.98989899  6.18181818  6.37373737  6.56565657
  6.75757576  6.94949495  7.14141414  7.33333333  7.52525253  7.71717172
  7.90909091  8.1010101   8.29292929  8.48484848  8.67676768  8.86868687
  9.06060606  9.25252525  9.44444444  9.63636364  9.82828283 10.02020202
 10.21212121 10.4040404  10.5959596  10.78787879 10.97979798 11.17171717
 11.36363636 11.55555556 11.74747475 11.93939394 12.13131313 12.32323232
 12.51515152 12.70707071 12.8989899  13.09090909 13.28282828 13.47474747
 13.66666667 13.85858586 14.05050505 14.24242424 14.43434343 14.62626263
 14.81818182 15.01010101 15.2020202  15.39393939 15.58585859 15.77777778
 15.96969697 16.16161616 16.35353535 16.54545455 16

In [30]:
print(np.logspace(0,2,100))

[  1.           1.04761575   1.09749877   1.149757     1.20450354
   1.26185688   1.32194115   1.38488637   1.45082878   1.51991108
   1.59228279   1.66810054   1.7475284    1.83073828   1.91791026
   2.009233     2.10490414   2.20513074   2.3101297    2.42012826
   2.53536449   2.65608778   2.7825594    2.91505306   3.05385551
   3.19926714   3.35160265   3.51119173   3.67837977   3.85352859
   4.03701726   4.22924287   4.43062146   4.64158883   4.86260158
   5.09413801   5.33669923   5.59081018   5.85702082   6.13590727
   6.42807312   6.73415066   7.05480231   7.39072203   7.74263683
   8.11130831   8.49753436   8.90215085   9.32603347   9.77009957
  10.23531022  10.72267222  11.23324033  11.76811952  12.32846739
  12.91549665  13.53047775  14.17474163  14.84968262  15.55676144
  16.29750835  17.07352647  17.88649529  18.73817423  19.6304065
  20.56512308  21.5443469   22.5701972   23.64489413  24.77076356
  25.95024211  27.18588243  28.48035868  29.8364724   31.2571585
  32.7454916

In [31]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
print(a[2][1])

8


In [33]:
# similar to iloc in datahandling, first one represents the rows and second one represents the columns
print(a[:2,:2])

[[1 2]
 [4 5]]


In [34]:
print(a[2,:])

[7 8 9]


In [35]:
a = np.array([[1,2],[3,4],[5,6]])

In [36]:
#First one refers to the rows and second refers to the column
# 0th row and 0th column
# 1st row and 1st column
# 2nd row and 0th column
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [37]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [38]:
# equivalent of above in terms of np.array is
print(a[[0,0],[1,1]])

[2 2]


In [39]:
# equivalent of above in terms of np.array is
print(np.array([a[0,1],a[0,1]]))

[2 2]


In [40]:
a= np.array([[4,7,1],[2,5,7],[7,1,1]])
mask = a>3
print(mask)

[[ True  True False]
 [False  True  True]
 [ True False False]]


In [41]:
print(a[mask])

[4 7 5 7 7]


In [42]:
a= np.array([1,2,3,4,5,6,7])

In [43]:
print(a[a>2])

[3 4 5 6 7]


In [44]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [45]:
print(a+b)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [46]:
print(np.add(a,b))

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [47]:
print(a-b)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [48]:
print(np.subtract(a,b))

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [49]:
print(a*b)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [50]:
print(np.multiply(a,b))

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [51]:
print(a/b)

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [52]:
print(np.divide(a,b))

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [53]:
a =np.array([[1,4,9],[16,25,36]])
print(np.sqrt(a))

[[1. 2. 3.]
 [4. 5. 6.]]


In [54]:
print(a.sum())

91


In [55]:
print(a.min())

1


In [56]:
print(a.max())

36


In [57]:
print(a.cumsum(axis=1))

[[ 1  5 14]
 [16 41 77]]


In [58]:
print(a.mean())

15.166666666666666


In [59]:
print(np.median(a))

12.5


In [60]:
print(np.corrcoef(a))

[[1.         0.99633201]
 [0.99633201 1.        ]]


In [61]:
print(np.std(a))

12.212243401148248


In [62]:
# Broadcasting
np.arange(3)+5

array([5, 6, 7])

In [63]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [64]:
np.arange(3).reshape(3,1)+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [65]:
array=np.array([3,4.5,3+5j,0])

In [66]:
array.dtype

dtype('complex128')

In [67]:
array[np.isreal(array)]

array([3. +0.j, 4.5+0.j, 0. +0.j])

In [68]:
# Quadratic equation 
# x2-4x+3
np.roots([1,-4,3])

array([3., 1.])

# cenus data analysis


In [69]:
import os
#os.listdir()
os.chdir('E:\\datasciencecommon\\numpy')
os.listdir()

['file.csv', 'NUMPYBASICS.ipynb']

In [70]:
import warnings
warnings.filterwarnings('ignore')

In [71]:
path ='E:\\datasciencecommon\\numpy\\file.csv'

In [72]:
new_record = [[50,9,4,1,0,0,40,0]]

In [73]:
data = np.genfromtxt(path, delimiter=',', skip_header=1)

In [74]:
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [75]:
type(data)

numpy.ndarray

In [76]:
data.shape

(1000, 8)

In [77]:
census = np.concatenate((data, new_record), axis = 0)
census.shape

(1001, 8)

In [78]:
census

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [79]:
# extracting age column data alone
age = census[:,0]

In [80]:
age

array([39., 50., 38., ..., 40., 39., 50.])

In [81]:
#test_code = census[census[:,0]]

In [82]:
print("max_age =", age.max())

max_age = 90.0


In [83]:
print("min_age", age.min())

min_age 17.0


In [84]:
print("mean_age", age.mean())

mean_age 38.06293706293706


In [85]:
print("age_std", age.std())

age_std 13.341478176165857


In [86]:
print("age_sum", age.sum())

age_sum 38101.0


In [87]:
# creating new subsets basd on race
race_0= census[census[:,2]==0]
race_1= census[census[:,2]==1]
race_2= census[census[:,2]==2]
race_3= census[census[:,2]==3]
race_4= census[census[:,2]==4]


In [88]:
race_0

array([[34.,  4.,  0.,  1.,  0.,  0., 45.,  0.],
       [35., 10.,  0.,  0.,  0.,  0., 40.,  0.],
       [60.,  6.,  0.,  0.,  0.,  0., 10.,  0.],
       [51.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [25., 10.,  0.,  0.,  0.,  0., 20.,  0.],
       [20.,  9.,  0.,  1.,  0.,  0., 48.,  0.],
       [23., 10.,  0.,  0.,  0.,  0., 25.,  0.],
       [29.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [27., 12.,  0.,  1.,  0.,  0., 40.,  0.],
       [31., 12.,  0.,  0.,  0.,  0., 40.,  0.]])

In [89]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

In [90]:
# printing the length of above subsets
print('Race_0', len(race_0))
print('Race_1', len(race_1))
print('Race_2', len(race_2))
print('Race_3', len(race_3))
print('Race_4', len(race_4))

Race_0 10
Race_1 27
Race_2 110
Race_3 6
Race_4 848


In [91]:
# storing different race lengths with appropriate indexes
race_list = [len_0, len_1, len_2, len_3, len_4]

In [92]:
minority_race = race_list.index(min(race_list))

In [93]:
minority_race

3

In [94]:
# subsetting ndarray based on the age condition
senior_citizens = census[census[:,0]>60]

In [95]:
senior_citizens.shape

(61, 8)

In [96]:
# Doubt to clarify with grey atom's team
# working total hours of senior citizens
working_hours_sum = senior_citizens.sum(axis=0)[6]
working_hours_sum = sum(senior_citizens[0:,6])

In [97]:
working_hours_sum

1917.0

In [98]:
senior_citizens_len = len(senior_citizens)

In [99]:
senior_citizens_len

61

In [100]:
# avg working hours of senior citizens is
avg_working_hours = working_hours_sum/senior_citizens_len

In [101]:
print(avg_working_hours)

31.42622950819672


In [102]:
high = census[census[:,1]>10]
low  = census[census[:,1]<=10]

In [103]:
high

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [28., 13.,  2., ...,  0., 40.,  0.],
       ...,
       [45., 14.,  4., ...,  0., 45.,  0.],
       [48., 13.,  4., ...,  0., 58.,  1.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [104]:
avg_pay_high = high[:,7].mean()

In [105]:
avg_pay_low = low[:,7].mean()

In [106]:
print(avg_pay_high)
print(avg_pay_low)

0.42813455657492355
0.13649851632047477


In [107]:
import os
os.getcwd()

'E:\\datasciencecommon\\numpy'